from django.contrib import admin
from .models import *

admin.site.register(User)
admin.site.register(PlayerAssignment)
admin.site.register(CoachAssignment)
admin.site.register(Match)
admin.site.register(Planning)
admin.site.register(Squad)
admin.site.register(Registration)
admin.site.register(Competence)
admin.site.register(RuleCompetition)
admin.site.register(RuleDiscipline)
admin.site.register(Discipline)
admin.site.register(CompetitionEdition)
admin.site.register(Stage)
admin.site.register(Team)
admin.site.register(Locality)
admin.site.register(DisciplineCatalog)
admin.site.register(CountryCatalog)
admin.site.register(CountryItem)
admin.site.register(FormatCatalog)
admin.site.register(FormatItem)
admin.site.register(StageCompetition)